name: google_vision_flutter
description: Add Google Visions image labeling, face, logo, and landmark detection into your Flutter applications.
version: 2.0.0+5
repository: https://github.com/faithoflifedev/google_vision
homepage: https://github.com/faithoflifedev/google_vision/tree/main/packages/google_vision_flutter

# publish_to: none

topics:
  - api
  - widget
  - flutter
  - image
  - document

funding:
  - https://www.buymeacoffee.com/faithoflif2

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  dio: ^5.7.0
  flutter_image_converter: ^0.4.1
  google_vision: ^2.0.0+3
  # google_vision:
  #   path: ../google_vision
  image: ^4.3.0
  loggy: ^2.0.3

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
  grinder: ^0.9.5
  publish_tools: ^1.0.0+10
