name: google_vision
description: Allows you to add Google Visions image labeling, face, logo, and landmark detection, OCR, and detection of explicit content, into applications.
version: 1.0.8+4
repository: https://github.com/faithoflifedev/google_vision
homepage: https://github.com/faithoflifedev/google_vision

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  args: ^2.4.2
  color: ^3.0.0
  crypto_keys: ^0.3.0+1
  dio: ^5.2.1+1
  http: ^0.13.6
  image: ^4.0.17
  jose: ^0.3.3
  json_annotation: ^4.8.1
  retrofit: ^4.0.1
  universal_io: ^2.2.2

dev_dependencies:
  build_runner: ^2.4.5
  grinder: ^0.9.4
  json_serializable: ^6.7.0
  lints: ^2.1.1
  publish_tools: ^0.1.0+10
  retrofit_generator: ^7.0.7
  test: ^1.24.3

executables:
  vision:
