name: google_vision
description: Allows you to add Google Visions image labeling, face, logo, and landmark detection, OCR, and detection of explicit content, into applications.
version: 1.0.7+6
repository: https://github.com/faithoflifedev/google_vision
homepage: https://github.com/faithoflifedev/google_vision

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  args: ^2.4.0
  color: ^3.0.0
  crypto_keys: ^0.3.0+1
  dio: ^5.0.2

  http: ^0.13.5

  image: ^4.0.15
  jose: ^0.3.3
  json_annotation: ^4.8.0
  retrofit: ^4.0.1
  universal_io: ^2.0.4

dev_dependencies:
  build_runner: ^2.3.3
  grinder: ^0.9.3
  json_serializable: ^6.6.1
  lints: ^2.0.0
  publish_tools: ^0.1.0+9
  retrofit_generator: ^6.0.0+1
  test: ^1.23.1

executables:
  vision:
