name: vision_demo
description: A simple app to test the google_vision package

publish_to: none

version: 1.0.0+2

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  google_vision:
    path: ../../../
  image: ^4.0.15
  path_provider: ^2.0.11

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/service_credentials.json
    - assets/young-man-smiling-and-thumbs-up.jpg
